### ISSUE TITLE
`getattr` on Process instances raises TransitionNotAllowed on failure

### ISSUE THREAD

**Issue by khamenman** [Borderless360/django-logic#25]
```
getattr(tracking_event.tracking_event_process, 'gfdgdfg')

Traceback (most recent call last):
  File "/home/vagrant/env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-ebad20b256f2>", line 1, in <module>
    getattr(tracking_event.tracking_event_process, 'gfdgdfg')
  File "/home/vagrant/env/lib/python3.6/site-packages/django_logic/process.py", line 51, in __getattr__
    raise TransitionNotAllowed('Transition not allowed')
django_logic.exceptions.TransitionNotAllowed: Transition not allowed
```
Seems like a bug, attribute user's attempting to get might not even be a transition

**Comment by emil-balashov** [comment]
@khamenman good point. Now, it raises AttributeError if such a transition doesn't exist
